spring.application.name = bank

spring.datasource.url = jdbc:postgresql://localhost:5432/bankdb
spring.datasource.username = postgres
spring.datasource.password = p$db
spring.datasource.driver-class-name = org.postgresql.Driver

spring.sql.init.mode = always

spring.security.user.name = parth
spring.security.user.password = Ro45